// Generated tools/list payload. Regenerate with scripts/gen_tools.py if
// you change the tool set (or edit carefully by hand and validate as JSON).
#pragma once

static const char kMcpToolsJson[] =
    "{\"tools\":[{\"name\":\"screenshot\",\"description\":\"Capture the current Switch screen as a JPEG image (128"
    "0x720). Returns the image directly so you can see what is on screen.\",\"inputSchema\":{\"type\":\"object\""
    ",\"properties\":{\"stack\":{\"type\":\"string\",\"enum\":[\"screenshot\",\"default\",\"lcd\",\"recording\",\"lastframe\""
    "],\"description\":\"Layer stack to capture. Default: screenshot (what the Capture button sees).\"}}}},{\""
    "name\":\"tap_buttons\",\"description\":\"Press and release controller buttons (synchronous). A virtual Pro"
    " Controller is attached automatically. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN"
    ", LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"buttons"
    "\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Buttons to act on. Button names: A, B, X,"
    " Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\"},\"durationMs\":"
    "{\"type\":\"integer\",\"description\":\"How long to hold before releasing, in ms. Default 100, max 10000.\"}"
    ",\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also includes a screenshot taken "
    "after the input, saving a separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"descrip"
    "tion\":\"Delay before that screenshot in ms (lets the UI settle). Default 250.\"}},\"required\":[\"buttons"
    "\"]}},{\"name\":\"tap_sequence\",\"description\":\"Perform a sequence of button taps in one call, e.g. to na"
    "vigate menus. Each step presses its buttons, holds, releases, then waits before the next step. Butto"
    "n names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE"
    ".\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"taps\":{\"type\":\"array\",\"maxItems\":32,\"description\":\""
    "Sequence of taps (max 32).\",\"items\":{\"type\":\"object\",\"properties\":{\"buttons\":{\"type\":\"array\",\"items\""
    ":{\"type\":\"string\"},\"description\":\"Buttons to act on. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, M"
    "INUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\"},\"durationMs\":{\"type\":\"integer\",\"descri"
    "ption\":\"Hold time in ms. Default 100.\"},\"delayAfterMs\":{\"type\":\"integer\",\"description\":\"Pause after "
    "release in ms. Default 150.\"}},\"required\":[\"buttons\"]}},\"screenshot\":{\"type\":\"boolean\",\"description\""
    ":\"If true, the result also includes a screenshot taken after the input, saving a separate screenshot"
    " call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"description\":\"Delay before that screenshot in ms (le"
    "ts the UI settle). Default 250.\"}},\"required\":[\"taps\"]}},{\"name\":\"hold_buttons\",\"description\":\"Press"
    " buttons and keep them held until release_buttons or clear_input. Button names: A, B, X, Y, L, R, ZL"
    ", ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\",\"inputSchema\":{\"type\":\"obj"
    "ect\",\"properties\":{\"buttons\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Buttons to act"
    " on. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOM"
    "E, CAPTURE.\"},\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also includes a scre"
    "enshot taken after the input, saving a separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"inte"
    "ger\",\"description\":\"Delay before that screenshot in ms (lets the UI settle). Default 250.\"}},\"requir"
    "ed\":[\"buttons\"]}},{\"name\":\"release_buttons\",\"description\":\"Release previously held buttons.\",\"inputS"
    "chema\":{\"type\":\"object\",\"properties\":{\"buttons\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"descripti"
    "on\":\"Buttons to act on. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, "
    "LSTICK, RSTICK, HOME, CAPTURE.\"},\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result a"
    "lso includes a screenshot taken after the input, saving a separate screenshot call.\"},\"screenshotDel"
    "ayMs\":{\"type\":\"integer\",\"description\":\"Delay before that screenshot in ms (lets the UI settle). Defa"
    "ult 250.\"}},\"required\":[\"buttons\"]}},{\"name\":\"set_stick\",\"description\":\"Set an analog stick position"
    ". x/y range -1.0..1.0 (y=1.0 is up). With durationMs the stick recenters afterwards; without it the "
    "position persists until changed or clear_input.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"side\""
    ":{\"type\":\"string\",\"enum\":[\"left\",\"right\"]},\"x\":{\"type\":\"number\"},\"y\":{\"type\":\"number\"},\"durationMs\":"
    "{\"type\":\"integer\",\"description\":\"Hold time before recentering. Max 10000.\"},\"screenshot\":{\"type\":\"bo"
    "olean\",\"description\":\"If true, the result also includes a screenshot taken after the input, saving a"
    " separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"description\":\"Delay before that "
    "screenshot in ms (lets the UI settle). Default 250.\"}},\"required\":[\"side\"]}},{\"name\":\"clear_input\",\""
    "description\":\"Release all held buttons and recenter both sticks.\",\"inputSchema\":{\"type\":\"object\",\"pr"
    "operties\":{\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also includes a screens"
    "hot taken after the input, saving a separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer"
    "\",\"description\":\"Delay before that screenshot in ms (lets the UI settle). Default 250.\"}}}},{\"name\":"
    "\"status\",\"description\":\"Get server status: version, console firmware, virtual controller state, upti"
    "me, and battery percentage / charging state.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"nam"
    "e\":\"list_directory\",\"description\":\"List a directory on the SD card. Returns JSON with name/type/size"
    "/mtime per entry.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"description"
    "\":\"Absolute path on the SD card, e.g. /switch/myapp/log.txt\"}},\"required\":[\"path\"]}},{\"name\":\"read_f"
    "ile\",\"description\":\"Read a text file from the SD card (logs, configs). Returns up to 32 KB per call;"
    " use offset/length to page through larger files. A negative offset reads from the end of the file (t"
    "ail).\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"description\":\"Absolute "
    "path on the SD card, e.g. /switch/myapp/log.txt\"},\"offset\":{\"type\":\"integer\",\"description\":\"Byte off"
    "set; negative = from end of file.\"},\"length\":{\"type\":\"integer\",\"description\":\"Max bytes to read (cap"
    "ped at 32768).\"}},\"required\":[\"path\"]}},{\"name\":\"upload_file\",\"description\":\"Write a file to the SD "
    "card. content is base64-encoded and is streamed to disk, so size is limited only by SD space - but l"
    "arge binaries are cheaper to deploy via the raw HTTP API (curl -T file 'http://<ip>:<port>/files?pat"
    "h=...').\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"description\":\"Absolu"
    "te path on the SD card, e.g. /switch/myapp/log.txt\"},\"content\":{\"type\":\"string\",\"description\":\"Base6"
    "4-encoded file content.\"}},\"required\":[\"path\",\"content\"]}},{\"name\":\"delete_file\",\"description\":\"Dele"
    "te a file or empty directory on the SD card.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\""
    "type\":\"string\",\"description\":\"Absolute path on the SD card, e.g. /switch/myapp/log.txt\"}},\"required\""
    ":[\"path\"]}},{\"name\":\"hash_file\",\"description\":\"Compute the SHA-256 of a file on the SD card. The fil"
    "e is hashed in a streaming fashion (constant memory, any size), and only the 64-char hex digest is r"
    "eturned - not the file contents. Use this to verify an upload landed intact: pass the SHA-256 you ex"
    "pected as 'expected' and the result reports matched:true/false. Returns JSON: {algorithm, hash, size"
    "[, matched]}.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"description\":\"A"
    "bsolute path on the SD card, e.g. /switch/myapp/log.txt\"},\"expected\":{\"type\":\"string\",\"description\":"
    "\"Optional expected SHA-256 hex digest. When provided, the result includes a 'matched' boolean (case-"
    "insensitive comparison).\"}},\"required\":[\"path\"]}},{\"name\":\"create_token\",\"description\":\"Create a new"
    " bearer token for the raw HTTP API (returned as text). Useful when a tool call is impractical, e.g. "
    "uploading large files with curl: pass it as an 'Authorization: Bearer <token>' header. The token is "
    "a long-lived credential for this console - do not store it outside the current task. Revoke by delet"
    "ing its line from config/sys-autopilot/tokens.txt.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}}"
    ",{\"name\":\"revoke_token\",\"description\":\"Revoke a bearer token previously issued via create_token or t"
    "he OAuth login flow (removes it from tokens.txt). Use this to clean up tokens you created once they "
    "are no longer needed. Careful: revoking the token your own MCP connection uses will lock you out.\",\""
    "inputSchema\":{\"type\":\"object\",\"properties\":{\"token\":{\"type\":\"string\",\"description\":\"The token to rev"
    "oke.\"}},\"required\":[\"token\"]}},{\"name\":\"sleep\",\"description\":\"Put the console into sleep mode. WARNI"
    "NG: the server becomes unreachable immediately and CANNOT be woken remotely - a human must physicall"
    "y press a button on the console or a paired controller to wake it. Only use when explicitly asked to"
    ".\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"restart\",\"description\":\"Reboot the cons"
    "ole. WARNING: the server goes down immediately, and whether it returns without human help depends on"
    " the bootloader: setups that boot into a menu (e.g. Hekate without autoboot) require someone to manu"
    "ally re-launch the firmware. In-memory state (held buttons, virtual controller) is lost. Only use wh"
    "en explicitly asked to.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"power_off\",\"descr"
    "iption\":\"Fully power off the console. WARNING: the server becomes permanently unreachable - a human "
    "must physically press the power button to turn the console back on. Only use when explicitly asked t"
    "o.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"process_status\",\"description\":\"Check w"
    "hether the program with the given title id is currently running, and return its process id if so. Us"
    "e this to confirm a sysmodule actually came up after starting it, or actually went away after stoppi"
    "ng it.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"titleId\":{\"type\":\"string\",\"description\":\"Progr"
    "am (title) id as 16 hex digits, e.g. \\\"690000000000000d\\\". This is the id /titles reports, and the d"
    "irectory name under /atmosphere/contents for a sysmodule.\"}},\"required\":[\"titleId\"]}},{\"name\":\"proce"
    "ss_start\",\"description\":\"Launch the program with the given title id. Works for sysmodules under /atm"
    "osphere/contents whether or not they have a flags/boot2.flag, so a module can be kept out of the boo"
    "t sequence and started on demand instead. Fails if it is already running.\",\"inputSchema\":{\"type\":\"ob"
    "ject\",\"properties\":{\"titleId\":{\"type\":\"string\",\"description\":\"Program (title) id as 16 hex digits, e"
    ".g. \\\"690000000000000d\\\". This is the id /titles reports, and the directory name under /atmosphere/c"
    "ontents for a sysmodule.\"}},\"required\":[\"titleId\"]}},{\"name\":\"process_stop\",\"description\":\"Terminate"
    " the program with the given title id. WARNING: this is a hard kill, so the program does not get to s"
    "hut down cleanly; a sysmodule that holds system resources may leave them attached until the next reb"
    "oot. Fails if it is not running.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"titleId\":{\"type\":\"st"
    "ring\",\"description\":\"Program (title) id as 16 hex digits, e.g. \\\"690000000000000d\\\". This is the id "
    "/titles reports, and the directory name under /atmosphere/contents for a sysmodule.\"}},\"required\":[\""
    "titleId\"]}},{\"name\":\"process_restart\",\"description\":\"Stop the program with the given title id (if ru"
    "nning), wait for it to actually exit, then start it again. This is the normal way to load a rebuilt "
    "sysmodule after uploading its exefs.nsp, and avoids the race of starting it while the old process is"
    " still dying.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"titleId\":{\"type\":\"string\",\"description\""
    ":\"Program (title) id as 16 hex digits, e.g. \\\"690000000000000d\\\". This is the id /titles reports, an"
    "d the directory name under /atmosphere/contents for a sysmodule.\"}},\"required\":[\"titleId\"]}},{\"name\""
    ":\"get_theme\",\"description\":\"Get the system UI theme. Returns \\\"light\\\" or \\\"dark\\\".\",\"inputSchema\":{"
    "\"type\":\"object\",\"properties\":{}}},{\"name\":\"set_theme\",\"description\":\"Set the system UI theme (light "
    "or dark mode). NOTE: this updates the stored setting immediately, but the HOME menu only re-reads it"
    " when it reloads - so the visible change takes effect after sleep/wake or a reboot, not instantly.\","
    "\"inputSchema\":{\"type\":\"object\",\"properties\":{\"theme\":{\"type\":\"string\",\"enum\":[\"light\",\"dark\"]}},\"req"
    "uired\":[\"theme\"]}},{\"name\":\"get_nickname\",\"description\":\"Get the console's device nickname (the name"
    " shown on the network and in settings).\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"s"
    "et_nickname\",\"description\":\"Set the console's device nickname.\",\"inputSchema\":{\"type\":\"object\",\"prop"
    "erties\":{\"nickname\":{\"type\":\"string\",\"description\":\"New device nickname (max ~127 bytes).\"}},\"requir"
    "ed\":[\"nickname\"]}},{\"name\":\"get_brightness\",\"description\":\"Get the current screen brightness as a va"
    "lue from 0.0 (dimmest) to 1.0 (brightest).\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\""
    ":\"set_brightness\",\"description\":\"Set the screen brightness and apply it immediately. Note: if the co"
    "nsole has auto-brightness enabled it may adjust again on its own.\",\"inputSchema\":{\"type\":\"object\",\"p"
    "roperties\":{\"brightness\":{\"type\":\"number\",\"description\":\"0.0 (dimmest) to 1.0 (brightest).\"}},\"requi"
    "red\":[\"brightness\"]}},{\"name\":\"get_volume\",\"description\":\"Get the current master volume as a value f"
    "rom 0.0 (muted) to 1.0 (max).\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"set_volume\""
    ",\"description\":\"Set the master volume.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"volume\":{\"type"
    "\":\"number\",\"description\":\"0.0 (muted) to 1.0 (max).\"}},\"required\":[\"volume\"]}},{\"name\":\"airplane_mod"
    "e\",\"description\":\"Enable airplane mode (disable all wireless). WARNING: this disconnects the console"
    " from the network, so the server becomes unreachable immediately and CANNOT be re-enabled remotely -"
    " a human must turn wireless back on from the console. There is no remote 'disable airplane mode' for"
    " that reason. Only use when explicitly asked to.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{"
    "\"name\":\"list_installed_titles\",\"description\":\"List installed applications (titles) on the console. R"
    "eturns one line per title: 16-hex title id, content-meta version, storage (sd/nand/gamecard), and di"
    "splay name. Useful for confirming an install or finding a title id. Lists base applications only (no"
    "t updates or DLC).\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"get_dns\",\"description\""
    ":\"Get the console's current DNS configuration for the active network connection: whether it's automa"
    "tic (DHCP) or manual, and the primary/secondary DNS server addresses.\",\"inputSchema\":{\"type\":\"object"
    "\",\"properties\":{}}},{\"name\":\"set_dns\",\"description\":\"Set the active connection's DNS servers. Pass '"
    "primary' (and optional 'secondary') as IPv4 strings to set manual DNS, or 'automatic':true to revert"
    " to DHCP. Useful for pointing the console at a custom/black-hole DNS (e.g. 90DNS) to block Nintendo "
    "servers while staying on the LAN.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"automatic\":{\"type\":"
    "\"boolean\",\"description\":\"true = revert to DHCP DNS (ignores primary/secondary).\"},\"primary\":{\"type\":"
    "\"string\",\"description\":\"Primary DNS IPv4, e.g. \\\"207.246.121.77\\\".\"},\"secondary\":{\"type\":\"string\",\"d"
    "escription\":\"Optional secondary DNS IPv4.\"}}}},{\"name\":\"get_auto_time\",\"description\":\"Get whether th"
    "e clock is automatically synchronized over the internet. Returns \\\"enabled\\\" or \\\"disabled\\\".\",\"inpu"
    "tSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"set_auto_time\",\"description\":\"Enable or disable"
    " automatic internet clock synchronization. Disable it before setting the clock manually with set_dat"
    "etime, or the manual time is overwritten.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"enabled\":{\""
    "type\":\"boolean\"}},\"required\":[\"enabled\"]}},{\"name\":\"get_datetime\",\"description\":\"Get the console's c"
    "urrent local date, time, and timezone. Returns \\\"YYYY-MM-DD HH:MM:SS <timezone>\\\".\",\"inputSchema\":{\""
    "type\":\"object\",\"properties\":{}}},{\"name\":\"set_datetime\",\"description\":\"Set the console's clock. Prov"
    "ide any subset of date/time fields; omitted ones keep their current value. The time is interpreted i"
    "n the console's current timezone. (The timezone itself can't be changed remotely; set the date/time "
    "only.) If internet time sync is on, the OS may later re-sync - call set_auto_time(false) first to ma"
    "ke a manual time stick.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"year\":{\"type\":\"integer\",\"desc"
    "ription\":\"e.g. 2026\"},\"month\":{\"type\":\"integer\",\"description\":\"1-12\"},\"day\":{\"type\":\"integer\",\"descr"
    "iption\":\"1-31\"},\"hour\":{\"type\":\"integer\",\"description\":\"0-23\"},\"minute\":{\"type\":\"integer\",\"descripti"
    "on\":\"0-59\"},\"second\":{\"type\":\"integer\",\"description\":\"0-59\"}}}}]}";
