// Generated tools/list payload. Regenerate with scripts/gen_tools.py if
// you change the tool set (or edit carefully by hand and validate as JSON).
#pragma once

static const char kMcpToolsJson[] =
    "{\"tools\":[{\"name\":\"screenshot\",\"description\":\"Capture the current Switch screen as a JPEG image (128"
    "0x720). Returns the image directly so you can see what is on screen.\",\"inputSchema\":{\"type\":\"object\""
    ",\"properties\":{\"stack\":{\"type\":\"string\",\"enum\":[\"screenshot\",\"default\",\"lcd\",\"recording\",\"lastframe\""
    "],\"description\":\"Layer stack to capture. Default: screenshot (what the Capture button sees).\"}}}},{\""
    "name\":\"tap_buttons\",\"description\":\"Press and release controller buttons (synchronous). A virtual Pro"
    " Controller is attached automatically. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN"
    ", LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"buttons"
    "\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Buttons to act on. Button names: A, B, X,"
    " Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\"},\"durationMs\":"
    "{\"type\":\"integer\",\"description\":\"How long to hold before releasing, in ms. Default 100, max 10000.\"}"
    ",\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also includes a screenshot taken "
    "after the input, saving a separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"descrip"
    "tion\":\"Delay before that screenshot in ms (lets the UI settle). Default 250.\"}},\"required\":[\"buttons"
    "\"]}},{\"name\":\"tap_sequence\",\"description\":\"Perform a sequence of button taps in one call, e.g. to na"
    "vigate menus. Each step presses its buttons, holds, releases, then waits before the next step. Butto"
    "n names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE"
    ".\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"taps\":{\"type\":\"array\",\"maxItems\":32,\"description\":\""
    "Sequence of taps (max 32).\",\"items\":{\"type\":\"object\",\"properties\":{\"buttons\":{\"type\":\"array\",\"items\""
    ":{\"type\":\"string\"},\"description\":\"Buttons to act on. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, M"
    "INUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\"},\"durationMs\":{\"type\":\"integer\",\"descri"
    "ption\":\"Hold time in ms. Default 100.\"},\"delayAfterMs\":{\"type\":\"integer\",\"description\":\"Pause after "
    "release in ms. Default 150.\"}},\"required\":[\"buttons\"]}},\"screenshot\":{\"type\":\"boolean\",\"description\""
    ":\"If true, the result also includes a screenshot taken after the input, saving a separate screenshot"
    " call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"description\":\"Delay before that screenshot in ms (le"
    "ts the UI settle). Default 250.\"}},\"required\":[\"taps\"]}},{\"name\":\"hold_buttons\",\"description\":\"Press"
    " buttons and keep them held until release_buttons or clear_input. Button names: A, B, X, Y, L, R, ZL"
    ", ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\",\"inputSchema\":{\"type\":\"obj"
    "ect\",\"properties\":{\"buttons\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Buttons to act"
    " on. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOM"
    "E, CAPTURE.\"},\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also includes a scre"
    "enshot taken after the input, saving a separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"inte"
    "ger\",\"description\":\"Delay before that screenshot in ms (lets the UI settle). Default 250.\"}},\"requir"
    "ed\":[\"buttons\"]}},{\"name\":\"release_buttons\",\"description\":\"Release previously held buttons.\",\"inputS"
    "chema\":{\"type\":\"object\",\"properties\":{\"buttons\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"descripti"
    "on\":\"Buttons to act on. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, "
    "LSTICK, RSTICK, HOME, CAPTURE.\"},\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result a"
    "lso includes a screenshot taken after the input, saving a separate screenshot call.\"},\"screenshotDel"
    "ayMs\":{\"type\":\"integer\",\"description\":\"Delay before that screenshot in ms (lets the UI settle). Defa"
    "ult 250.\"}},\"required\":[\"buttons\"]}},{\"name\":\"set_stick\",\"description\":\"Set an analog stick position"
    ". x/y range -1.0..1.0 (y=1.0 is up). With durationMs the stick recenters afterwards; without it the "
    "position persists until changed or clear_input.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"side\""
    ":{\"type\":\"string\",\"enum\":[\"left\",\"right\"]},\"x\":{\"type\":\"number\"},\"y\":{\"type\":\"number\"},\"durationMs\":"
    "{\"type\":\"integer\",\"description\":\"Hold time before recentering. Max 10000.\"},\"screenshot\":{\"type\":\"bo"
    "olean\",\"description\":\"If true, the result also includes a screenshot taken after the input, saving a"
    " separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"description\":\"Delay before that "
    "screenshot in ms (lets the UI settle). Default 250.\"}},\"required\":[\"side\"]}},{\"name\":\"tap_screen\",\"d"
    "escription\":\"Tap the touch screen at a pixel coordinate. Coordinates are in the same 1280x720 space "
    "as the screenshot tool, so you can read them straight off the image: x 0-1279 left to right, y 0-719"
    " top to bottom. Only reaches the console in handheld mode (docked, the panel is off).\",\"inputSchema\""
    ":{\"type\":\"object\",\"properties\":{\"x\":{\"type\":\"integer\",\"description\":\"0-1279, from the left edge.\"},\""
    "y\":{\"type\":\"integer\",\"description\":\"0-719, from the top edge.\"},\"durationMs\":{\"type\":\"integer\",\"desc"
    "ription\":\"How long the finger stays down. Default 100, min 32, max 10000. Raise it for a long press."
    "\"},\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also includes a screenshot take"
    "n after the input, saving a separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"descr"
    "iption\":\"Delay before that screenshot in ms (lets the UI settle). Default 250.\"}},\"required\":[\"x\",\"y"
    "\"]}},{\"name\":\"swipe_screen\",\"description\":\"Drag a finger across the touch screen, e.g. to scroll a l"
    "ist or flick a page. Same 1280x720 coordinate space as the screenshot tool. The gesture is interpola"
    "ted over durationMs, which is what makes scrolling register - a fast swipe flicks, a slow one drags."
    "\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"fromX\":{\"type\":\"integer\",\"description\":\"Start x, 0-1"
    "279.\"},\"fromY\":{\"type\":\"integer\",\"description\":\"Start y, 0-719.\"},\"toX\":{\"type\":\"integer\",\"descripti"
    "on\":\"End x, 0-1279.\"},\"toY\":{\"type\":\"integer\",\"description\":\"End y, 0-719.\"},\"durationMs\":{\"type\":\"i"
    "nteger\",\"description\":\"Time from start to end. Default 300, max 10000.\"},\"screenshot\":{\"type\":\"boole"
    "an\",\"description\":\"If true, the result also includes a screenshot taken after the input, saving a se"
    "parate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"description\":\"Delay before that scr"
    "eenshot in ms (lets the UI settle). Default 250.\"}},\"required\":[\"fromX\",\"fromY\",\"toX\",\"toY\"]}},{\"nam"
    "e\":\"clear_input\",\"description\":\"Release all held buttons and recenter both sticks.\",\"inputSchema\":{\""
    "type\":\"object\",\"properties\":{\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also "
    "includes a screenshot taken after the input, saving a separate screenshot call.\"},\"screenshotDelayMs"
    "\":{\"type\":\"integer\",\"description\":\"Delay before that screenshot in ms (lets the UI settle). Default "
    "250.\"}}}},{\"name\":\"status\",\"description\":\"Get server status: version, console firmware, virtual cont"
    "roller state, uptime, and battery percentage / charging state.\",\"inputSchema\":{\"type\":\"object\",\"prop"
    "erties\":{}}},{\"name\":\"list_directory\",\"description\":\"List a directory on the SD card. Returns JSON w"
    "ith name/type/size/mtime per entry.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"st"
    "ring\",\"description\":\"Absolute path on the SD card, e.g. /switch/myapp/log.txt\"}},\"required\":[\"path\"]"
    "}},{\"name\":\"read_file\",\"description\":\"Read a text file from the SD card (logs, configs). Returns up "
    "to 32 KB per call; use offset/length to page through larger files. A negative offset reads from the "
    "end of the file (tail).\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"descr"
    "iption\":\"Absolute path on the SD card, e.g. /switch/myapp/log.txt\"},\"offset\":{\"type\":\"integer\",\"desc"
    "ription\":\"Byte offset; negative = from end of file.\"},\"length\":{\"type\":\"integer\",\"description\":\"Max "
    "bytes to read (capped at 32768).\"}},\"required\":[\"path\"]}},{\"name\":\"upload_file\",\"description\":\"Write"
    " a file to the SD card. content is base64-encoded and is streamed to disk, so size is limited only b"
    "y SD space - but large binaries are cheaper to deploy via the raw HTTP API (curl -T file 'http://<ip"
    ">:<port>/files?path=...').\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"de"
    "scription\":\"Absolute path on the SD card, e.g. /switch/myapp/log.txt\"},\"content\":{\"type\":\"string\",\"d"
    "escription\":\"Base64-encoded file content.\"}},\"required\":[\"path\",\"content\"]}},{\"name\":\"delete_file\",\""
    "description\":\"Delete a file or empty directory on the SD card.\",\"inputSchema\":{\"type\":\"object\",\"prop"
    "erties\":{\"path\":{\"type\":\"string\",\"description\":\"Absolute path on the SD card, e.g. /switch/myapp/log"
    ".txt\"}},\"required\":[\"path\"]}},{\"name\":\"hash_file\",\"description\":\"Compute the SHA-256 of a file on th"
    "e SD card. The file is hashed in a streaming fashion (constant memory, any size), and only the 64-ch"
    "ar hex digest is returned - not the file contents. Use this to verify an upload landed intact: pass "
    "the SHA-256 you expected as 'expected' and the result reports matched:true/false. Returns JSON: {alg"
    "orithm, hash, size[, matched]}.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string"
    "\",\"description\":\"Absolute path on the SD card, e.g. /switch/myapp/log.txt\"},\"expected\":{\"type\":\"stri"
    "ng\",\"description\":\"Optional expected SHA-256 hex digest. When provided, the result includes a 'match"
    "ed' boolean (case-insensitive comparison).\"}},\"required\":[\"path\"]}},{\"name\":\"create_token\",\"descript"
    "ion\":\"Create a new bearer token for the raw HTTP API (returned as text). Useful when a tool call is "
    "impractical, e.g. uploading large files with curl: pass it as an 'Authorization: Bearer <token>' hea"
    "der. The token is a long-lived credential for this console - do not store it outside the current tas"
    "k. Revoke by deleting its line from config/sys-autopilot/tokens.txt.\",\"inputSchema\":{\"type\":\"object\""
    ",\"properties\":{}}},{\"name\":\"revoke_token\",\"description\":\"Revoke a bearer token previously issued via"
    " create_token or the OAuth login flow (removes it from tokens.txt). Use this to clean up tokens you "
    "created once they are no longer needed. Careful: revoking the token your own MCP connection uses wil"
    "l lock you out.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"token\":{\"type\":\"string\",\"description\""
    ":\"The token to revoke.\"}},\"required\":[\"token\"]}},{\"name\":\"sleep\",\"description\":\"Put the console into"
    " sleep mode. WARNING: the server becomes unreachable immediately and CANNOT be woken remotely - a hu"
    "man must physically press a button on the console or a paired controller to wake it. Only use when e"
    "xplicitly asked to.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"restart\",\"description"
    "\":\"Reboot the console. WARNING: the server goes down immediately, and whether it returns without hum"
    "an help depends on the bootloader: setups that boot into a menu (e.g. Hekate without autoboot) requi"
    "re someone to manually re-launch the firmware. In-memory state (held buttons, virtual controller) is"
    " lost. Only use when explicitly asked to.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":"
    "\"power_off\",\"description\":\"Fully power off the console. WARNING: the server becomes permanently unre"
    "achable - a human must physically press the power button to turn the console back on. Only use when "
    "explicitly asked to.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"process_status\",\"des"
    "cription\":\"Check whether the program with the given title id is currently running, and return its pr"
    "ocess id if so. Use this to confirm a sysmodule actually came up after starting it, or actually went"
    " away after stopping it.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"titleId\":{\"type\":\"string\",\"d"
    "escription\":\"Program (title) id as 16 hex digits, e.g. \\\"690000000000000d\\\". This is the id /titles "
    "reports, and the directory name under /atmosphere/contents for a sysmodule.\"}},\"required\":[\"titleId\""
    "]}},{\"name\":\"process_start\",\"description\":\"Launch the program with the given title id. Works for sys"
    "modules under /atmosphere/contents whether or not they have a flags/boot2.flag, so a module can be k"
    "ept out of the boot sequence and started on demand instead. Fails if it is already running.\",\"inputS"
    "chema\":{\"type\":\"object\",\"properties\":{\"titleId\":{\"type\":\"string\",\"description\":\"Program (title) id a"
    "s 16 hex digits, e.g. \\\"690000000000000d\\\". This is the id /titles reports, and the directory name u"
    "nder /atmosphere/contents for a sysmodule.\"}},\"required\":[\"titleId\"]}},{\"name\":\"process_stop\",\"descr"
    "iption\":\"Terminate the program with the given title id. WARNING: this is a hard kill, so the program"
    " does not get to shut down cleanly; a sysmodule that holds system resources may leave them attached "
    "until the next reboot. Fails if it is not running.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"ti"
    "tleId\":{\"type\":\"string\",\"description\":\"Program (title) id as 16 hex digits, e.g. \\\"690000000000000d\\"
    "\". This is the id /titles reports, and the directory name under /atmosphere/contents for a sysmodule"
    ".\"}},\"required\":[\"titleId\"]}},{\"name\":\"process_restart\",\"description\":\"Stop the program with the giv"
    "en title id (if running), wait for it to actually exit, then start it again. This is the normal way "
    "to load a rebuilt sysmodule after uploading its exefs.nsp, and avoids the race of starting it while "
    "the old process is still dying.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"titleId\":{\"type\":\"str"
    "ing\",\"description\":\"Program (title) id as 16 hex digits, e.g. \\\"690000000000000d\\\". This is the id /"
    "titles reports, and the directory name under /atmosphere/contents for a sysmodule.\"}},\"required\":[\"t"
    "itleId\"]}},{\"name\":\"get_theme\",\"description\":\"Get the system UI theme. Returns \\\"light\\\" or \\\"dark\\\""
    ".\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"set_theme\",\"description\":\"Set the syste"
    "m UI theme (light or dark mode). NOTE: this updates the stored setting immediately, but the HOME men"
    "u only re-reads it when it reloads - so the visible change takes effect after sleep/wake or a reboot"
    ", not instantly.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"theme\":{\"type\":\"string\",\"enum\":[\"lig"
    "ht\",\"dark\"]}},\"required\":[\"theme\"]}},{\"name\":\"get_nickname\",\"description\":\"Get the console's device "
    "nickname (the name shown on the network and in settings).\",\"inputSchema\":{\"type\":\"object\",\"propertie"
    "s\":{}}},{\"name\":\"set_nickname\",\"description\":\"Set the console's device nickname.\",\"inputSchema\":{\"ty"
    "pe\":\"object\",\"properties\":{\"nickname\":{\"type\":\"string\",\"description\":\"New device nickname (max ~127 "
    "bytes).\"}},\"required\":[\"nickname\"]}},{\"name\":\"get_brightness\",\"description\":\"Get the current screen "
    "brightness as a value from 0.0 (dimmest) to 1.0 (brightest).\",\"inputSchema\":{\"type\":\"object\",\"proper"
    "ties\":{}}},{\"name\":\"set_brightness\",\"description\":\"Set the screen brightness and apply it immediatel"
    "y. Note: if the console has auto-brightness enabled it may adjust again on its own.\",\"inputSchema\":{"
    "\"type\":\"object\",\"properties\":{\"brightness\":{\"type\":\"number\",\"description\":\"0.0 (dimmest) to 1.0 (bri"
    "ghtest).\"}},\"required\":[\"brightness\"]}},{\"name\":\"get_volume\",\"description\":\"Get the current master v"
    "olume as a value from 0.0 (muted) to 1.0 (max).\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\""
    "name\":\"set_volume\",\"description\":\"Set the master volume.\",\"inputSchema\":{\"type\":\"object\",\"properties"
    "\":{\"volume\":{\"type\":\"number\",\"description\":\"0.0 (muted) to 1.0 (max).\"}},\"required\":[\"volume\"]}},{\"n"
    "ame\":\"airplane_mode\",\"description\":\"Enable airplane mode (disable all wireless). WARNING: this disco"
    "nnects the console from the network, so the server becomes unreachable immediately and CANNOT be re-"
    "enabled remotely - a human must turn wireless back on from the console. There is no remote 'disable "
    "airplane mode' for that reason. Only use when explicitly asked to.\",\"inputSchema\":{\"type\":\"object\",\""
    "properties\":{}}},{\"name\":\"list_installed_titles\",\"description\":\"List installed applications (titles)"
    " on the console. Returns one line per title: 16-hex title id, content-meta version, storage (sd/nand"
    "/gamecard), and display name. Useful for confirming an install or finding a title id. Lists base app"
    "lications only (not updates or DLC).\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"get_"
    "dns\",\"description\":\"Get the console's current DNS configuration for the active network connection: w"
    "hether it's automatic (DHCP) or manual, and the primary/secondary DNS server addresses.\",\"inputSchem"
    "a\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"set_dns\",\"description\":\"Set the active connection's D"
    "NS servers. Pass 'primary' (and optional 'secondary') as IPv4 strings to set manual DNS, or 'automat"
    "ic':true to revert to DHCP. Useful for pointing the console at a custom/black-hole DNS (e.g. 90DNS) "
    "to block Nintendo servers while staying on the LAN.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"a"
    "utomatic\":{\"type\":\"boolean\",\"description\":\"true = revert to DHCP DNS (ignores primary/secondary).\"},"
    "\"primary\":{\"type\":\"string\",\"description\":\"Primary DNS IPv4, e.g. \\\"207.246.121.77\\\".\"},\"secondary\":{"
    "\"type\":\"string\",\"description\":\"Optional secondary DNS IPv4.\"}}}},{\"name\":\"get_auto_time\",\"descriptio"
    "n\":\"Get whether the clock is automatically synchronized over the internet. Returns \\\"enabled\\\" or \\\""
    "disabled\\\".\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"set_auto_time\",\"description\":"
    "\"Enable or disable automatic internet clock synchronization. Disable it before setting the clock man"
    "ually with set_datetime, or the manual time is overwritten.\",\"inputSchema\":{\"type\":\"object\",\"propert"
    "ies\":{\"enabled\":{\"type\":\"boolean\"}},\"required\":[\"enabled\"]}},{\"name\":\"get_datetime\",\"description\":\"G"
    "et the console's current local date, time, and timezone. Returns \\\"YYYY-MM-DD HH:MM:SS <timezone>\\\"."
    "\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"set_datetime\",\"description\":\"Set the con"
    "sole's clock. Provide any subset of date/time fields; omitted ones keep their current value. The tim"
    "e is interpreted in the console's current timezone. (The timezone itself can't be changed remotely; "
    "set the date/time only.) If internet time sync is on, the OS may later re-sync - call set_auto_time("
    "false) first to make a manual time stick.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"year\":{\"typ"
    "e\":\"integer\",\"description\":\"e.g. 2026\"},\"month\":{\"type\":\"integer\",\"description\":\"1-12\"},\"day\":{\"type"
    "\":\"integer\",\"description\":\"1-31\"},\"hour\":{\"type\":\"integer\",\"description\":\"0-23\"},\"minute\":{\"type\":\"i"
    "nteger\",\"description\":\"0-59\"},\"second\":{\"type\":\"integer\",\"description\":\"0-59\"}}}}]}";
