// Generated tools/list payload. Regenerate with scripts/gen_tools.py if
// you change the tool set (or edit carefully by hand and validate as JSON).
#pragma once

static const char kMcpToolsJson[] =
    "{\"tools\":[{\"name\":\"screenshot\",\"description\":\"Capture the current Switch screen as a JPEG image (128"
    "0x720). Returns the image directly so you can see what is on screen.\",\"inputSchema\":{\"type\":\"object\""
    ",\"properties\":{\"stack\":{\"type\":\"string\",\"enum\":[\"screenshot\",\"default\",\"lcd\",\"recording\",\"lastframe\""
    "],\"description\":\"Layer stack to capture. Default: screenshot (what the Capture button sees).\"}}}},{\""
    "name\":\"tap_buttons\",\"description\":\"Press and release controller buttons (synchronous). A virtual Pro"
    " Controller is attached automatically. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN"
    ", LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"buttons"
    "\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Buttons to act on. Button names: A, B, X,"
    " Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\"},\"durationMs\":"
    "{\"type\":\"integer\",\"description\":\"How long to hold before releasing, in ms. Default 100, max 10000.\"}"
    ",\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also includes a screenshot taken "
    "after the input, saving a separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"descrip"
    "tion\":\"Delay before that screenshot in ms (lets the UI settle). Default 250.\"}},\"required\":[\"buttons"
    "\"]}},{\"name\":\"tap_sequence\",\"description\":\"Perform a sequence of button taps in one call, e.g. to na"
    "vigate menus. Each step presses its buttons, holds, releases, then waits before the next step. Butto"
    "n names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE"
    ".\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"taps\":{\"type\":\"array\",\"maxItems\":32,\"description\":\""
    "Sequence of taps (max 32).\",\"items\":{\"type\":\"object\",\"properties\":{\"buttons\":{\"type\":\"array\",\"items\""
    ":{\"type\":\"string\"},\"description\":\"Buttons to act on. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, M"
    "INUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\"},\"durationMs\":{\"type\":\"integer\",\"descri"
    "ption\":\"Hold time in ms. Default 100.\"},\"delayAfterMs\":{\"type\":\"integer\",\"description\":\"Pause after "
    "release in ms. Default 150.\"}},\"required\":[\"buttons\"]}},\"screenshot\":{\"type\":\"boolean\",\"description\""
    ":\"If true, the result also includes a screenshot taken after the input, saving a separate screenshot"
    " call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"description\":\"Delay before that screenshot in ms (le"
    "ts the UI settle). Default 250.\"}},\"required\":[\"taps\"]}},{\"name\":\"hold_buttons\",\"description\":\"Press"
    " buttons and keep them held until release_buttons or clear_input. Button names: A, B, X, Y, L, R, ZL"
    ", ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\",\"inputSchema\":{\"type\":\"obj"
    "ect\",\"properties\":{\"buttons\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Buttons to act"
    " on. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOM"
    "E, CAPTURE.\"},\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also includes a scre"
    "enshot taken after the input, saving a separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"inte"
    "ger\",\"description\":\"Delay before that screenshot in ms (lets the UI settle). Default 250.\"}},\"requir"
    "ed\":[\"buttons\"]}},{\"name\":\"release_buttons\",\"description\":\"Release previously held buttons.\",\"inputS"
    "chema\":{\"type\":\"object\",\"properties\":{\"buttons\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"descripti"
    "on\":\"Buttons to act on. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, "
    "LSTICK, RSTICK, HOME, CAPTURE.\"},\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result a"
    "lso includes a screenshot taken after the input, saving a separate screenshot call.\"},\"screenshotDel"
    "ayMs\":{\"type\":\"integer\",\"description\":\"Delay before that screenshot in ms (lets the UI settle). Defa"
    "ult 250.\"}},\"required\":[\"buttons\"]}},{\"name\":\"set_stick\",\"description\":\"Set an analog stick position"
    ". x/y range -1.0..1.0 (y=1.0 is up). With durationMs the stick recenters afterwards; without it the "
    "position persists until changed or clear_input.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"side\""
    ":{\"type\":\"string\",\"enum\":[\"left\",\"right\"]},\"x\":{\"type\":\"number\"},\"y\":{\"type\":\"number\"},\"durationMs\":"
    "{\"type\":\"integer\",\"description\":\"Hold time before recentering. Max 10000.\"},\"screenshot\":{\"type\":\"bo"
    "olean\",\"description\":\"If true, the result also includes a screenshot taken after the input, saving a"
    " separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"description\":\"Delay before that "
    "screenshot in ms (lets the UI settle). Default 250.\"}},\"required\":[\"side\"]}},{\"name\":\"tap_screen\",\"d"
    "escription\":\"Tap the touch screen at a pixel coordinate. Coordinates are in the same 1280x720 space "
    "as the screenshot tool, so you can read them straight off the image: x 0-1279 left to right, y 0-719"
    " top to bottom. Only reaches the console in handheld mode (docked, the panel is off).\",\"inputSchema\""
    ":{\"type\":\"object\",\"properties\":{\"x\":{\"type\":\"integer\",\"description\":\"0-1279, from the left edge.\"},\""
    "y\":{\"type\":\"integer\",\"description\":\"0-719, from the top edge.\"},\"durationMs\":{\"type\":\"integer\",\"desc"
    "ription\":\"How long the finger stays down. Default 100, min 32, max 10000. Raise it for a long press."
    "\"},\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also includes a screenshot take"
    "n after the input, saving a separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"descr"
    "iption\":\"Delay before that screenshot in ms (lets the UI settle). Default 250.\"}},\"required\":[\"x\",\"y"
    "\"]}},{\"name\":\"swipe_screen\",\"description\":\"Drag a finger across the touch screen, e.g. to scroll a l"
    "ist or flick a page. Same 1280x720 coordinate space as the screenshot tool. The gesture is interpola"
    "ted over durationMs, which is what makes scrolling register - a fast swipe flicks, a slow one drags."
    "\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"fromX\":{\"type\":\"integer\",\"description\":\"Start x, 0-1"
    "279.\"},\"fromY\":{\"type\":\"integer\",\"description\":\"Start y, 0-719.\"},\"toX\":{\"type\":\"integer\",\"descripti"
    "on\":\"End x, 0-1279.\"},\"toY\":{\"type\":\"integer\",\"description\":\"End y, 0-719.\"},\"durationMs\":{\"type\":\"i"
    "nteger\",\"description\":\"Time from start to end. Default 300, max 10000.\"},\"screenshot\":{\"type\":\"boole"
    "an\",\"description\":\"If true, the result also includes a screenshot taken after the input, saving a se"
    "parate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"description\":\"Delay before that scr"
    "eenshot in ms (lets the UI settle). Default 250.\"}},\"required\":[\"fromX\",\"fromY\",\"toX\",\"toY\"]}},{\"nam"
    "e\":\"clear_input\",\"description\":\"Release all held buttons and recenter both sticks.\",\"inputSchema\":{\""
    "type\":\"object\",\"properties\":{\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also "
    "includes a screenshot taken after the input, saving a separate screenshot call.\"},\"screenshotDelayMs"
    "\":{\"type\":\"integer\",\"description\":\"Delay before that screenshot in ms (lets the UI settle). Default "
    "250.\"}}}},{\"name\":\"status\",\"description\":\"Get server status: version, console firmware, virtual cont"
    "roller state, uptime, and battery percentage / charging state.\",\"inputSchema\":{\"type\":\"object\",\"prop"
    "erties\":{}}},{\"name\":\"list_directory\",\"description\":\"List a directory on the SD card. Returns JSON w"
    "ith name/type/size/mtime per entry.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"st"
    "ring\",\"description\":\"Absolute path on the SD card, e.g. /switch/myapp/log.txt\"}},\"required\":[\"path\"]"
    "}},{\"name\":\"read_file\",\"description\":\"Read a text file from the SD card (logs, configs). Returns up "
    "to 32 KB per call; use offset/length to page through larger files. A negative offset reads from the "
    "end of the file (tail).\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"descr"
    "iption\":\"Absolute path on the SD card, e.g. /switch/myapp/log.txt\"},\"offset\":{\"type\":\"integer\",\"desc"
    "ription\":\"Byte offset; negative = from end of file.\"},\"length\":{\"type\":\"integer\",\"description\":\"Max "
    "bytes to read (capped at 32768).\"}},\"required\":[\"path\"]}},{\"name\":\"upload_file\",\"description\":\"Write"
    " a file to the SD card. content is base64-encoded and is streamed to disk, so size is limited only b"
    "y SD space - but large binaries are cheaper to deploy via the raw HTTP API (curl -T file 'http://<ip"
    ">:<port>/files?path=...').\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"de"
    "scription\":\"Absolute path on the SD card, e.g. /switch/myapp/log.txt\"},\"content\":{\"type\":\"string\",\"d"
    "escription\":\"Base64-encoded file content.\"}},\"required\":[\"path\",\"content\"]}},{\"name\":\"move_file\",\"de"
    "scription\":\"Rename or move a file or directory on the SD card. Parent directories of the destination"
    " are created; an existing destination is never overwritten.\",\"inputSchema\":{\"type\":\"object\",\"propert"
    "ies\":{\"path\":{\"type\":\"string\",\"description\":\"Absolute path on the SD card, e.g. /switch/myapp/log.tx"
    "t\"},\"to\":{\"type\":\"string\",\"description\":\"Absolute destination path on the SD card, e.g. /switch/myap"
    "p/log.old.txt\"}},\"required\":[\"path\",\"to\"]}},{\"name\":\"delete_file\",\"description\":\"Delete a file or em"
    "pty directory on the SD card.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\","
    "\"description\":\"Absolute path on the SD card, e.g. /switch/myapp/log.txt\"}},\"required\":[\"path\"]}},{\"n"
    "ame\":\"hash_file\",\"description\":\"Compute the SHA-256 of a file on the SD card. The file is hashed in "
    "a streaming fashion (constant memory, any size), and only the 64-char hex digest is returned - not t"
    "he file contents. Use this to verify an upload landed intact: pass the SHA-256 you expected as 'expe"
    "cted' and the result reports matched:true/false. Returns JSON: {algorithm, hash, size[, matched]}.\","
    "\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"description\":\"Absolute path on"
    " the SD card, e.g. /switch/myapp/log.txt\"},\"expected\":{\"type\":\"string\",\"description\":\"Optional expec"
    "ted SHA-256 hex digest. When provided, the result includes a 'matched' boolean (case-insensitive com"
    "parison).\"}},\"required\":[\"path\"]}},{\"name\":\"create_token\",\"description\":\"Create a new bearer token f"
    "or the raw HTTP API (returned as text). Useful when a tool call is impractical, e.g. uploading large"
    " files with curl: pass it as an 'Authorization: Bearer <token>' header. The token is a long-lived cr"
    "edential for this console - do not store it outside the current task. Revoke by deleting its line fr"
    "om config/sys-autopilot/tokens.txt.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"revok"
    "e_token\",\"description\":\"Revoke a bearer token previously issued via create_token or the OAuth login "
    "flow (removes it from tokens.txt). Use this to clean up tokens you created once they are no longer n"
    "eeded. Careful: revoking the token your own MCP connection uses will lock you out.\",\"inputSchema\":{\""
    "type\":\"object\",\"properties\":{\"token\":{\"type\":\"string\",\"description\":\"The token to revoke.\"}},\"requir"
    "ed\":[\"token\"]}},{\"name\":\"sleep\",\"description\":\"Put the console into sleep mode. WARNING: the server "
    "becomes unreachable immediately and CANNOT be woken remotely - a human must physically press a butto"
    "n on the console or a paired controller to wake it. Only use when explicitly asked to.\",\"inputSchema"
    "\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"restart\",\"description\":\"Reboot the console. WARNING: t"
    "he server goes down immediately, and whether it returns without human help depends on the bootloader"
    ": setups that boot into a menu (e.g. Hekate without autoboot) require someone to manually re-launch "
    "the firmware. In-memory state (held buttons, virtual controller) is lost. Only use when explicitly a"
    "sked to.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"power_off\",\"description\":\"Fully "
    "power off the console. WARNING: the server becomes permanently unreachable - a human must physically"
    " press the power button to turn the console back on. Only use when explicitly asked to.\",\"inputSchem"
    "a\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"process_status\",\"description\":\"Check whether the prog"
    "ram with the given title id is currently running, and return its process id if so. Use this to confi"
    "rm a sysmodule actually came up after starting it, or actually went away after stopping it.\",\"inputS"
    "chema\":{\"type\":\"object\",\"properties\":{\"titleId\":{\"type\":\"string\",\"description\":\"Program (title) id a"
    "s 16 hex digits, e.g. \\\"690000000000000d\\\". This is the id /titles reports, and the directory name u"
    "nder /atmosphere/contents for a sysmodule.\"}},\"required\":[\"titleId\"]}},{\"name\":\"process_start\",\"desc"
    "ription\":\"Launch the program with the given title id. Works for sysmodules under /atmosphere/content"
    "s whether or not they have a flags/boot2.flag, so a module can be kept out of the boot sequence and "
    "started on demand instead. Fails if it is already running.\",\"inputSchema\":{\"type\":\"object\",\"properti"
    "es\":{\"titleId\":{\"type\":\"string\",\"description\":\"Program (title) id as 16 hex digits, e.g. \\\"690000000"
    "000000d\\\". This is the id /titles reports, and the directory name under /atmosphere/contents for a s"
    "ysmodule.\"}},\"required\":[\"titleId\"]}},{\"name\":\"process_stop\",\"description\":\"Terminate the program wi"
    "th the given title id. WARNING: this is a hard kill, so the program does not get to shut down cleanl"
    "y; a sysmodule that holds system resources may leave them attached until the next reboot. Fails if i"
    "t is not running.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"titleId\":{\"type\":\"string\",\"descript"
    "ion\":\"Program (title) id as 16 hex digits, e.g. \\\"690000000000000d\\\". This is the id /titles reports"
    ", and the directory name under /atmosphere/contents for a sysmodule.\"}},\"required\":[\"titleId\"]}},{\"n"
    "ame\":\"process_restart\",\"description\":\"Stop the program with the given title id (if running), wait fo"
    "r it to actually exit, then start it again. This is the normal way to load a rebuilt sysmodule after"
    " uploading its exefs.nsp, and avoids the race of starting it while the old process is still dying.\","
    "\"inputSchema\":{\"type\":\"object\",\"properties\":{\"titleId\":{\"type\":\"string\",\"description\":\"Program (titl"
    "e) id as 16 hex digits, e.g. \\\"690000000000000d\\\". This is the id /titles reports, and the directory"
    " name under /atmosphere/contents for a sysmodule.\"}},\"required\":[\"titleId\"]}},{\"name\":\"get_theme\",\"d"
    "escription\":\"Get the system UI theme. Returns \\\"light\\\" or \\\"dark\\\".\",\"inputSchema\":{\"type\":\"object\""
    ",\"properties\":{}}},{\"name\":\"set_theme\",\"description\":\"Set the system UI theme (light or dark mode). "
    "NOTE: this updates the stored setting immediately, but the HOME menu only re-reads it when it reload"
    "s - so the visible change takes effect after sleep/wake or a reboot, not instantly.\",\"inputSchema\":{"
    "\"type\":\"object\",\"properties\":{\"theme\":{\"type\":\"string\",\"enum\":[\"light\",\"dark\"]}},\"required\":[\"theme\""
    "]}},{\"name\":\"get_nickname\",\"description\":\"Get the console's device nickname (the name shown on the n"
    "etwork and in settings).\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"set_nickname\",\"d"
    "escription\":\"Set the console's device nickname.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"nickn"
    "ame\":{\"type\":\"string\",\"description\":\"New device nickname (max ~127 bytes).\"}},\"required\":[\"nickname\""
    "]}},{\"name\":\"get_brightness\",\"description\":\"Get the current screen brightness as a value from 0.0 (d"
    "immest) to 1.0 (brightest).\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"set_brightnes"
    "s\",\"description\":\"Set the screen brightness and apply it immediately. Note: if the console has auto-"
    "brightness enabled it may adjust again on its own.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"br"
    "ightness\":{\"type\":\"number\",\"description\":\"0.0 (dimmest) to 1.0 (brightest).\"}},\"required\":[\"brightne"
    "ss\"]}},{\"name\":\"get_volume\",\"description\":\"Get the current master volume as a value from 0.0 (muted)"
    " to 1.0 (max).\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"set_volume\",\"description\":"
    "\"Set the master volume.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"volume\":{\"type\":\"number\",\"des"
    "cription\":\"0.0 (muted) to 1.0 (max).\"}},\"required\":[\"volume\"]}},{\"name\":\"airplane_mode\",\"description"
    "\":\"Enable airplane mode (disable all wireless). WARNING: this disconnects the console from the netwo"
    "rk, so the server becomes unreachable immediately and CANNOT be re-enabled remotely - a human must t"
    "urn wireless back on from the console. There is no remote 'disable airplane mode' for that reason. O"
    "nly use when explicitly asked to.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"list_in"
    "stalled_titles\",\"description\":\"List installed applications (titles) on the console. Returns one line"
    " per title: 16-hex title id, content-meta version, storage (sd/nand/gamecard), and display name. Use"
    "ful for confirming an install or finding a title id. Lists base applications only (not updates or DL"
    "C).\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"get_dns\",\"description\":\"Get the conso"
    "le's current DNS configuration for the active network connection: whether it's automatic (DHCP) or m"
    "anual, and the primary/secondary DNS server addresses.\",\"inputSchema\":{\"type\":\"object\",\"properties\":"
    "{}}},{\"name\":\"set_dns\",\"description\":\"Set the active connection's DNS servers. Pass 'primary' (and o"
    "ptional 'secondary') as IPv4 strings to set manual DNS, or 'automatic':true to revert to DHCP. Usefu"
    "l for pointing the console at a custom/black-hole DNS (e.g. 90DNS) to block Nintendo servers while s"
    "taying on the LAN.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"automatic\":{\"type\":\"boolean\",\"desc"
    "ription\":\"true = revert to DHCP DNS (ignores primary/secondary).\"},\"primary\":{\"type\":\"string\",\"descr"
    "iption\":\"Primary DNS IPv4, e.g. \\\"207.246.121.77\\\".\"},\"secondary\":{\"type\":\"string\",\"description\":\"Op"
    "tional secondary DNS IPv4.\"}}}},{\"name\":\"get_auto_time\",\"description\":\"Get whether the clock is auto"
    "matically synchronized over the internet. Returns \\\"enabled\\\" or \\\"disabled\\\".\",\"inputSchema\":{\"type"
    "\":\"object\",\"properties\":{}}},{\"name\":\"set_auto_time\",\"description\":\"Enable or disable automatic inte"
    "rnet clock synchronization. Disable it before setting the clock manually with set_datetime, or the m"
    "anual time is overwritten.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"enabled\":{\"type\":\"boolean\""
    "}},\"required\":[\"enabled\"]}},{\"name\":\"get_datetime\",\"description\":\"Get the console's current local da"
    "te, time, and timezone. Returns \\\"YYYY-MM-DD HH:MM:SS <timezone>\\\".\",\"inputSchema\":{\"type\":\"object\","
    "\"properties\":{}}},{\"name\":\"set_datetime\",\"description\":\"Set the console's clock. Provide any subset "
    "of date/time fields; omitted ones keep their current value. The time is interpreted in the console's"
    " current timezone. (The timezone itself can't be changed remotely; set the date/time only.) If inter"
    "net time sync is on, the OS may later re-sync - call set_auto_time(false) first to make a manual tim"
    "e stick.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"year\":{\"type\":\"integer\",\"description\":\"e.g. "
    "2026\"},\"month\":{\"type\":\"integer\",\"description\":\"1-12\"},\"day\":{\"type\":\"integer\",\"description\":\"1-31\"}"
    ",\"hour\":{\"type\":\"integer\",\"description\":\"0-23\"},\"minute\":{\"type\":\"integer\",\"description\":\"0-59\"},\"se"
    "cond\":{\"type\":\"integer\",\"description\":\"0-59\"}}}}]}";
