#!/usr/bin/env python3
"""Generates source/common/explorer_page.h from source/common/explorer.html.

The explorer UI is a single HTML file so it can be edited (and opened straight
from disk) like any web page; this bakes it into the sysmodule as a C string so
the server can serve it without touching the SD card.
"""
import os

here = os.path.dirname(__file__)
src = os.path.join(here, "..", "source", "common", "explorer.html")
out = os.path.join(here, "..", "source", "common", "explorer_page.h")

with open(src, encoding="utf-8") as f:
    page = f.read()

if "\r" in page:
    raise SystemExit("explorer.html must use LF line endings")


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t")


lines = [
    "// Generated from explorer.html. Regenerate with scripts/gen_explorer.py",
    "// after editing the page -- do not edit this file by hand.",
    "#pragma once",
    "",
    "static const char kExplorerHtml[] =",
]
for line in page.rstrip("\n").split("\n"):
    lines.append('    "%s\\n"' % c_escape(line))
lines[-1] += ";"

with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", os.path.normpath(out), "(%d bytes of HTML)" % len(page))
